package View;

import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import com.mongodb.client.result.DeleteResult;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.bson.Document;

/**
 *
 * @author danie
 */
public class Formulario_Encuesta extends javax.swing.JFrame {

    private MongoDatabase db;
    private MongoCollection<Document> encuestas;
    private MongoCollection<Document> preguntas;

    int xMouse, yMouse;

    /**
     * Creates new form Formulario_Encuesta
     */
    public Formulario_Encuesta() {
        try {
            MongoClient mongoClient = MongoClients.create("mongodb://localhost:27017");
            db = mongoClient.getDatabase("encuestasAED");
            encuestas = db.getCollection("encuestas");
            preguntas = db.getCollection("preguntas");
            System.out.println("Conexión exitosa");

        } catch (Exception ex) {
            Logger.getLogger(Formulario_Encuesta.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtNoEnc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomEnc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPregu1 = new javax.swing.JTextField();
        txtPregu2 = new javax.swing.JTextField();
        txtPregu3 = new javax.swing.JTextField();
        txtPregu4 = new javax.swing.JTextField();
        txtPregu5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtRespu1 = new javax.swing.JTextField();
        txtRespu2 = new javax.swing.JTextField();
        txtRespu3 = new javax.swing.JTextField();
        txtRespu4 = new javax.swing.JTextField();
        txtRespu5 = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaActualizar = new javax.swing.JTextArea();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        savePreguntasBtn = new javax.swing.JButton();
        doEncuestaBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel1.setText("FORMULARIO");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 6, -1, -1));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 1188, 10));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Nº Encuesta:");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 52, -1, -1));

        txtNoEnc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNoEnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoEncActionPerformed(evt);
            }
        });
        bg.add(txtNoEnc, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 50, 75, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Nombre de la Encuesta:");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 90, -1, -1));

        txtNomEnc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bg.add(txtNomEnc, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 88, 271, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("Nº");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 133, 37, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("Pregunta");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 133, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setText("1.-");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 170, 37, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setText("2.-");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 211, 37, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setText("3.-");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 251, 37, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setText("4.-");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 289, 37, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel10.setText("5.-");
        bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 325, 43, -1));

        txtPregu1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPregu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregu1ActionPerformed(evt);
            }
        });
        bg.add(txtPregu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 168, 237, -1));

        txtPregu2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bg.add(txtPregu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 209, 237, -1));

        txtPregu3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bg.add(txtPregu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 249, 237, -1));

        txtPregu4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bg.add(txtPregu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 287, 237, -1));

        txtPregu5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bg.add(txtPregu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 323, 237, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel11.setText("Respuesta");
        bg.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 133, -1, -1));

        txtRespu1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bg.add(txtRespu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 168, 245, -1));

        txtRespu2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bg.add(txtRespu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 209, 245, -1));

        txtRespu3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bg.add(txtRespu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 249, 245, -1));

        txtRespu4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bg.add(txtRespu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 287, 245, -1));

        txtRespu5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bg.add(txtRespu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 323, 245, -1));

        btnAgregar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnAgregar.setText("Agregar encuesta");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        bg.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 412, -1, -1));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 382, 1176, 10));

        btnBuscar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnBuscar.setText("Buscar encuesta");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        bg.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 412, -1, -1));

        btnEditar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnEditar.setText("Editar encuesta");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        bg.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 412, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnEliminar.setText("Eliminar encuesta");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        bg.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 412, -1, -1));

        btnLimpiar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnLimpiar.setText("Limpiar campos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        bg.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 412, -1, -1));

        txtaActualizar.setEditable(false);
        txtaActualizar.setColumns(20);
        txtaActualizar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtaActualizar.setRows(5);
        jScrollPane1.setViewportView(txtaActualizar);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 420, 320));

        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn.setPreferredSize(new java.awt.Dimension(51, 50));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
        });

        exitTxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setPreferredSize(new java.awt.Dimension(51, 50));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1139, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1190, 50));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        bg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 740, 250));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        savePreguntasBtn.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        savePreguntasBtn.setText("Guardar preguntas");
        savePreguntasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePreguntasBtnActionPerformed(evt);
            }
        });

        doEncuestaBtn.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        doEncuestaBtn.setText("Hacer encuesta");
        doEncuestaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doEncuestaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(savePreguntasBtn)
                .addGap(53, 53, 53)
                .addComponent(doEncuestaBtn)
                .addContainerGap(820, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savePreguntasBtn)
                    .addComponent(doEncuestaBtn))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 1190, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoEncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoEncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoEncActionPerformed

    private void txtPregu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregu1ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        String noEnc = txtNoEnc.getText().trim();
        String nomEnc = txtNomEnc.getText().trim();

        if (noEnc.isEmpty() || nomEnc.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Los campos 'Nº ENCUESTA' y 'TITULO DE ENCUESTA' son obligatorios.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si los campos obligatorios están vacíos
        }

        // Verificar que txtNoEnc sea un número
        try {
            Integer.parseInt(noEnc); // Intentamos convertir el texto a un número
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El campo 'Nº ENCUESTA' debe ser un número.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si no es un número
        }

        // Crear el documento con los datos del formulario
        Document document = new Document()
                .append("Nº ENCUESTA", noEnc)
                .append("TITULO DE ENCUESTA", nomEnc)
                .append("PREGUNTA 1", txtPregu1.getText().trim())
                .append("RESPUESTA 1", txtRespu1.getText().trim())
                .append("PREGUNTA 2", txtPregu2.getText().trim())
                .append("RESPUESTA 2", txtRespu2.getText().trim())
                .append("PREGUNTA 3", txtPregu3.getText().trim())
                .append("RESPUESTA 3", txtRespu3.getText().trim())
                .append("PREGUNTA 4", txtPregu4.getText().trim())
                .append("RESPUESTA 4", txtRespu4.getText().trim())
                .append("PREGUNTA 5", txtPregu5.getText().trim())
                .append("RESPUESTA 5", txtRespu5.getText().trim());

        // Insertar el documento en la colección
        encuestas.insertOne(document);

        System.out.println("Encuesta agregada correctamente.");

        // Limpiar los campos después de agregar la encuesta
        btnLimpiarActionPerformed(evt);

        // Alert
        JOptionPane.showMessageDialog(null, "¡Se ha agregado correctamente!",
                "Acción realizada", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // Crear el filtro para encontrar la encuesta por su número
        Document filtro = new Document("Nº ENCUESTA", txtNoEnc.getText().trim());

        // Crear los cambios a aplicar
        Document actualizar = new Document()
                .append("TITULO DE ENCUESTA", txtNomEnc.getText().trim())
                .append("PREGUNTA 1", txtPregu1.getText().trim())
                .append("RESPUESTA 1", txtRespu1.getText().trim())
                .append("PREGUNTA 2", txtPregu2.getText().trim())
                .append("RESPUESTA 2", txtRespu2.getText().trim())
                .append("PREGUNTA 3", txtPregu3.getText().trim())
                .append("RESPUESTA 3", txtRespu3.getText().trim())
                .append("PREGUNTA 4", txtPregu4.getText().trim())
                .append("RESPUESTA 4", txtRespu4.getText().trim())
                .append("PREGUNTA 5", txtPregu5.getText().trim())
                .append("RESPUESTA 5", txtRespu5.getText().trim());

        // Actualizar la encuesta en la base de datos
        encuestas.updateOne(Filters.eq("Nº ENCUESTA", txtNoEnc.getText().trim()),
                new Document("$set", actualizar));

        System.out.println("Encuesta actualizada correctamente.");

        btnLimpiarActionPerformed(evt);

        // Alert
        JOptionPane.showMessageDialog(null, "¡Se ha editado correctamente!",
                "Acción realizada", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // Buscar en la colección usando el número de encuesta
        FindIterable<Document> resultados = encuestas.find(Filters.eq("Nº ENCUESTA", txtNoEnc.getText().trim()));

        // Si hay resultados, llenamos los campos con los datos de la encuesta
        for (Document doc : resultados) {
            txtNomEnc.setText(doc.getString("TITULO DE ENCUESTA"));
            txtPregu1.setText(doc.getString("PREGUNTA 1"));
            txtRespu1.setText(doc.getString("RESPUESTA 1"));
            txtPregu2.setText(doc.getString("PREGUNTA 2"));
            txtRespu2.setText(doc.getString("RESPUESTA 2"));
            txtPregu3.setText(doc.getString("PREGUNTA 3"));
            txtRespu3.setText(doc.getString("RESPUESTA 3"));
            txtPregu4.setText(doc.getString("PREGUNTA 4"));
            txtRespu4.setText(doc.getString("RESPUESTA 4"));
            txtPregu5.setText(doc.getString("PREGUNTA 5"));
            txtRespu5.setText(doc.getString("RESPUESTA 5"));

            System.out.println("Encuesta encontrada: " + doc.toJson());
            break; // Solo mostramos el primer resultado
        }

        // Obtener todas las encuestas y convertirlas en una lista
        List<Document> documentos = encuestas.find(Filters.eq("Nº ENCUESTA", txtNoEnc.getText().trim())).into(new ArrayList<>());

        // Limpiar el área de texto
        txtaActualizar.setText("");

        if (documentos.isEmpty()) {
            txtaActualizar.setText("No hay encuestas almacenadas.");
        } else {
            for (Document doc : documentos) {
                txtaActualizar.append("\n" + doc.toJson());
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // Crear el filtro para encontrar la encuesta por el número de encuesta
        Document filtro = new Document("Nº ENCUESTA", txtNoEnc.getText().trim());

        // Eliminar el documento que coincide con el filtro
        DeleteResult resultado = encuestas.deleteOne(filtro);

        if (resultado.getDeletedCount() > 0) {
            System.out.println("Encuesta eliminada correctamente.");
            btnLimpiarActionPerformed(evt);
            // Alert
            JOptionPane.showMessageDialog(null, "¡Se ha eliminado correctamente!",
                    "Acción realizada", JOptionPane.INFORMATION_MESSAGE);
        } else {
            System.out.println("No se encontró la encuesta para eliminar.");
            JOptionPane.showMessageDialog(null, "No existe la encuesta con el número " + txtNoEnc.getText().trim(),
                    "Acción realizada", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtNoEnc.setText("");
        txtNomEnc.setText("");
        txtPregu1.setText("");
        txtRespu1.setText("");
        txtPregu2.setText("");
        txtRespu2.setText("");
        txtPregu3.setText("");
        txtRespu3.setText("");
        txtPregu4.setText("");
        txtRespu4.setText("");
        txtPregu5.setText("");
        txtRespu5.setText("");

        txtaActualizar.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_exitBtnMouseEntered

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitBtn.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(new Color(214, 217, 223));
        exitBtn.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void savePreguntasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePreguntasBtnActionPerformed

        String noEnc = txtNoEnc.getText().trim();
        String nomEnc = txtNomEnc.getText().trim();

        if (noEnc.isEmpty() || nomEnc.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Los campos 'Nº ENCUESTA' y 'TITULO DE ENCUESTA' son obligatorios.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si los campos obligatorios están vacíos
        }

        // Verificar que txtNoEnc sea un número
        try {
            Integer.parseInt(noEnc); // Intentamos convertir el texto a un número
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El campo 'Nº ENCUESTA' debe ser un número.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si no es un número
        }

        // Crear el documento con los datos del formulario
        Document document = new Document()
                .append("Nº ENCUESTA", noEnc)
                .append("TITULO DE ENCUESTA", nomEnc)
                .append("PREGUNTA 1", txtPregu1.getText().trim())
                .append("PREGUNTA 2", txtPregu2.getText().trim())
                .append("PREGUNTA 3", txtPregu3.getText().trim())
                .append("PREGUNTA 4", txtPregu4.getText().trim())
                .append("PREGUNTA 5", txtPregu5.getText().trim());

        // Insertar el documento en la colección
        preguntas.insertOne(document);

        System.out.println("Preguntas agregadas correctamente.");

        // Limpiar los campos después de agregar la encuesta
        btnLimpiarActionPerformed(evt);

        // Alert
        JOptionPane.showMessageDialog(null, "¡Se ha agregado correctamente!",
                "Acción realizada", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_savePreguntasBtnActionPerformed

    private void doEncuestaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doEncuestaBtnActionPerformed
        // Buscar en la colección usando el número de encuesta
        FindIterable<Document> resultados = preguntas.find(Filters.eq("Nº ENCUESTA", txtNoEnc.getText().trim()));

        // Si hay resultados, llenamos los campos con los datos de la encuesta
        for (Document doc : resultados) {
            txtNomEnc.setText(doc.getString("TITULO DE ENCUESTA"));
            txtPregu1.setText(doc.getString("PREGUNTA 1"));
            txtPregu2.setText(doc.getString("PREGUNTA 2"));
            txtPregu3.setText(doc.getString("PREGUNTA 3"));
            txtPregu4.setText(doc.getString("PREGUNTA 4"));
            txtPregu5.setText(doc.getString("PREGUNTA 5"));

            System.out.println("Encuesta encontrada: " + doc.toJson());
            break; // Solo mostramos el primer resultado
        }

        // Obtener todas las preguntas y convertirlas en una lista
        List<Document> documentos = preguntas.find(Filters.eq("Nº ENCUESTA", txtNoEnc.getText().trim())).into(new ArrayList<>());

        // Limpiar el área de texto
        txtaActualizar.setText("");

        if (documentos.isEmpty()) {
            txtaActualizar.setText("No hay respuestas almacenadas.");
        } else {
            for (Document doc : documentos) {
                txtaActualizar.append("\n" + doc.toJson());
            }
        }
    }//GEN-LAST:event_doEncuestaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_Encuesta().setVisible(true);
            }
        });
    }

    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    public void setBtnAgregar(JButton btnAgregar) {
        this.btnAgregar = btnAgregar;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public void setBtnBuscar(JButton btnBuscar) {
        this.btnBuscar = btnBuscar;
    }

    public JButton getBtnEditar() {
        return btnEditar;
    }

    public void setBtnEditar(JButton btnEditar) {
        this.btnEditar = btnEditar;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public void setBtnEliminar(JButton btnEliminar) {
        this.btnEliminar = btnEliminar;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    public void setBtnLimpiar(JButton btnLimpiar) {
        this.btnLimpiar = btnLimpiar;
    }

    public JTextField getTxtNoEnc() {
        return txtNoEnc;
    }

    public void setTxtNoEnc(JTextField txtNoEnc) {
        this.txtNoEnc = txtNoEnc;
    }

    public JTextField getTxtNomEnc() {
        return txtNomEnc;
    }

    public void setTxtNomEnc(JTextField txtNomEnc) {
        this.txtNomEnc = txtNomEnc;
    }

    public JTextField getTxtPregu1() {
        return txtPregu1;
    }

    public void setTxtPregu1(JTextField txtPregu1) {
        this.txtPregu1 = txtPregu1;
    }

    public JTextField getTxtPregu2() {
        return txtPregu2;
    }

    public void setTxtPregu2(JTextField txtPregu2) {
        this.txtPregu2 = txtPregu2;
    }

    public JTextField getTxtPregu3() {
        return txtPregu3;
    }

    public void setTxtPregu3(JTextField txtPregu3) {
        this.txtPregu3 = txtPregu3;
    }

    public JTextField getTxtPregu4() {
        return txtPregu4;
    }

    public void setTxtPregu4(JTextField txtPregu4) {
        this.txtPregu4 = txtPregu4;
    }

    public JTextField getTxtPregu5() {
        return txtPregu5;
    }

    public void setTxtPregu5(JTextField txtPregu5) {
        this.txtPregu5 = txtPregu5;
    }

    public JTextField getTxtRespu1() {
        return txtRespu1;
    }

    public void setTxtRespu1(JTextField txtRespu1) {
        this.txtRespu1 = txtRespu1;
    }

    public JTextField getTxtRespu2() {
        return txtRespu2;
    }

    public void setTxtRespu2(JTextField txtRespu2) {
        this.txtRespu2 = txtRespu2;
    }

    public JTextField getTxtRespu3() {
        return txtRespu3;
    }

    public void setTxtRespu3(JTextField txtRespu3) {
        this.txtRespu3 = txtRespu3;
    }

    public JTextField getTxtRespu4() {
        return txtRespu4;
    }

    public void setTxtRespu4(JTextField txtRespu4) {
        this.txtRespu4 = txtRespu4;
    }

    public JTextField getTxtRespu5() {
        return txtRespu5;
    }

    public void setTxtRespu5(JTextField txtRespu5) {
        this.txtRespu5 = txtRespu5;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JPanel content;
    private javax.swing.JButton doEncuestaBtn;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton savePreguntasBtn;
    private javax.swing.JTextField txtNoEnc;
    private javax.swing.JTextField txtNomEnc;
    private javax.swing.JTextField txtPregu1;
    private javax.swing.JTextField txtPregu2;
    private javax.swing.JTextField txtPregu3;
    private javax.swing.JTextField txtPregu4;
    private javax.swing.JTextField txtPregu5;
    private javax.swing.JTextField txtRespu1;
    private javax.swing.JTextField txtRespu2;
    private javax.swing.JTextField txtRespu3;
    private javax.swing.JTextField txtRespu4;
    private javax.swing.JTextField txtRespu5;
    private javax.swing.JTextArea txtaActualizar;
    // End of variables declaration//GEN-END:variables
}
