package View;

import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import com.mongodb.client.result.DeleteResult;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JTextField;
import org.bson.Document;

/**
 *
 * @author danie
 */
public class Formulario_Encuesta extends javax.swing.JFrame {

    private MongoDatabase db;
    private MongoCollection<Document> encuestas;

    /**
     * Creates new form Formulario_Encuesta
     */
    public Formulario_Encuesta() {
        try {
            MongoClient mongoClient = MongoClients.create("mongodb://localhost:27017");
            db = mongoClient.getDatabase("encuestasAED");
            encuestas = db.getCollection("encuestas");
            System.out.println("Conexión exitosa");
        } catch (Exception ex) {
                Logger.getLogger(Formulario_Encuesta.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtNoEnc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomEnc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPregu1 = new javax.swing.JTextField();
        txtPregu2 = new javax.swing.JTextField();
        txtPregu3 = new javax.swing.JTextField();
        txtPregu4 = new javax.swing.JTextField();
        txtPregu5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtRespu1 = new javax.swing.JTextField();
        txtRespu2 = new javax.swing.JTextField();
        txtRespu3 = new javax.swing.JTextField();
        txtRespu4 = new javax.swing.JTextField();
        txtRespu5 = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FORMULARIO");

        jLabel2.setText("Nº Encuesta:");

        txtNoEnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoEncActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre de la Encuesta:");

        jLabel4.setText("Nº");

        jLabel5.setText("Pregunta");

        jLabel6.setText("1.-");

        jLabel7.setText("2.-");

        jLabel8.setText("3.-");

        jLabel9.setText("4.-");

        jLabel10.setText("5.-");

        txtPregu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregu1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Respuesta");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNoEnc, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(txtNomEnc, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addComponent(txtPregu1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                                .addComponent(txtPregu2)
                                .addComponent(txtPregu3)
                                .addComponent(txtPregu4)
                                .addComponent(txtPregu5))
                            .addGap(89, 89, 89)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(378, 378, 378)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addComponent(txtRespu1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(txtRespu2)
                    .addComponent(txtRespu3)
                    .addComponent(txtRespu4)
                    .addComponent(txtRespu5))
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnAgregar)
                .addGap(60, 60, 60)
                .addComponent(btnBuscar)
                .addGap(66, 66, 66)
                .addComponent(btnEditar)
                .addGap(69, 69, 69)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnLimpiar)
                .addGap(42, 42, 42))
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNoEnc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNomEnc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPregu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRespu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPregu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRespu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPregu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRespu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPregu4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRespu4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPregu5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRespu5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnBuscar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoEncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoEncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoEncActionPerformed

    private void txtPregu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregu1ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // Crear el documento con los datos del formulario
        Document document = new Document()
                .append("Nº ENCUESTA", txtNoEnc.getText().trim())
                .append("TITULO DE ENCUESTA", txtNomEnc.getText().trim())
                .append("PREGUNTA 1", txtPregu1.getText().trim())
                .append("RESPUESTA 1", txtRespu1.getText().trim())
                .append("PREGUNTA 2", txtPregu2.getText().trim())
                .append("RESPUESTA 2", txtRespu2.getText().trim())
                .append("PREGUNTA 3", txtPregu3.getText().trim())
                .append("RESPUESTA 3", txtRespu3.getText().trim())
                .append("PREGUNTA 4", txtPregu4.getText().trim())
                .append("RESPUESTA 4", txtRespu4.getText().trim())
                .append("PREGUNTA 5", txtPregu5.getText().trim())
                .append("RESPUESTA 5", txtRespu5.getText().trim());

        // Insertar el documento en la colección
        encuestas.insertOne(document);

        System.out.println("Encuesta agregada correctamente.");

        // Limpiar los campos después de agregar la encuesta
        btnLimpiarActionPerformed(evt);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // Crear el filtro para encontrar la encuesta por su número
        Document filtro = new Document("Nº ENCUESTA", txtNoEnc.getText().trim());

        // Crear los cambios a aplicar
        Document actualizar = new Document()
                .append("TITULO DE ENCUESTA", txtNomEnc.getText().trim())
                .append("PREGUNTA 1", txtPregu1.getText().trim())
                .append("RESPUESTA 1", txtRespu1.getText().trim())
                .append("PREGUNTA 2", txtPregu2.getText().trim())
                .append("RESPUESTA 2", txtRespu2.getText().trim())
                .append("PREGUNTA 3", txtPregu3.getText().trim())
                .append("RESPUESTA 3", txtRespu3.getText().trim())
                .append("PREGUNTA 4", txtPregu4.getText().trim())
                .append("RESPUESTA 4", txtRespu4.getText().trim())
                .append("PREGUNTA 5", txtPregu5.getText().trim())
                .append("RESPUESTA 5", txtRespu5.getText().trim());

        // Actualizar la encuesta en la base de datos
        encuestas.updateOne(Filters.eq("Nº ENCUESTA", txtNoEnc.getText().trim()),
                new Document("$set", actualizar));

        System.out.println("Encuesta actualizada correctamente.");

        btnLimpiarActionPerformed(evt);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // Buscar en la colección usando el número de encuesta
        FindIterable<Document> resultados = encuestas.find(Filters.eq("Nº ENCUESTA", txtNoEnc.getText().trim()));

        // Si hay resultados, llenamos los campos con los datos de la encuesta
        for (Document doc : resultados) {
            txtNomEnc.setText(doc.getString("TITULO DE ENCUESTA"));
            txtPregu1.setText(doc.getString("PREGUNTA 1"));
            txtRespu1.setText(doc.getString("RESPUESTA 1"));
            txtPregu2.setText(doc.getString("PREGUNTA 2"));
            txtRespu2.setText(doc.getString("RESPUESTA 2"));
            txtPregu3.setText(doc.getString("PREGUNTA 3"));
            txtRespu3.setText(doc.getString("RESPUESTA 3"));
            txtPregu4.setText(doc.getString("PREGUNTA 4"));
            txtRespu4.setText(doc.getString("RESPUESTA 4"));
            txtPregu5.setText(doc.getString("PREGUNTA 5"));
            txtRespu5.setText(doc.getString("RESPUESTA 5"));

            System.out.println("Encuesta encontrada: " + doc.toJson());
            break; // Solo mostramos el primer resultado
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // Crear el filtro para encontrar la encuesta por el número de encuesta
        Document filtro = new Document("Nº ENCUESTA", txtNoEnc.getText().trim());

        // Eliminar el documento que coincide con el filtro
        DeleteResult resultado = encuestas.deleteOne(filtro);

        if (resultado.getDeletedCount() > 0) {
            System.out.println("Encuesta eliminada correctamente.");
        } else {
            System.out.println("No se encontró la encuesta para eliminar.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtNoEnc.setText("");
        txtNomEnc.setText("");
        txtPregu1.setText("");
        txtRespu1.setText("");
        txtPregu2.setText("");
        txtRespu2.setText("");
        txtPregu3.setText("");
        txtRespu3.setText("");
        txtPregu4.setText("");
        txtRespu4.setText("");
        txtPregu5.setText("");
        txtRespu5.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_Encuesta().setVisible(true);
            }
        });
    }

    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    public void setBtnAgregar(JButton btnAgregar) {
        this.btnAgregar = btnAgregar;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public void setBtnBuscar(JButton btnBuscar) {
        this.btnBuscar = btnBuscar;
    }

    public JButton getBtnEditar() {
        return btnEditar;
    }

    public void setBtnEditar(JButton btnEditar) {
        this.btnEditar = btnEditar;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public void setBtnEliminar(JButton btnEliminar) {
        this.btnEliminar = btnEliminar;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    public void setBtnLimpiar(JButton btnLimpiar) {
        this.btnLimpiar = btnLimpiar;
    }

    public JTextField getTxtNoEnc() {
        return txtNoEnc;
    }

    public void setTxtNoEnc(JTextField txtNoEnc) {
        this.txtNoEnc = txtNoEnc;
    }

    public JTextField getTxtNomEnc() {
        return txtNomEnc;
    }

    public void setTxtNomEnc(JTextField txtNomEnc) {
        this.txtNomEnc = txtNomEnc;
    }

    public JTextField getTxtPregu1() {
        return txtPregu1;
    }

    public void setTxtPregu1(JTextField txtPregu1) {
        this.txtPregu1 = txtPregu1;
    }

    public JTextField getTxtPregu2() {
        return txtPregu2;
    }

    public void setTxtPregu2(JTextField txtPregu2) {
        this.txtPregu2 = txtPregu2;
    }

    public JTextField getTxtPregu3() {
        return txtPregu3;
    }

    public void setTxtPregu3(JTextField txtPregu3) {
        this.txtPregu3 = txtPregu3;
    }

    public JTextField getTxtPregu4() {
        return txtPregu4;
    }

    public void setTxtPregu4(JTextField txtPregu4) {
        this.txtPregu4 = txtPregu4;
    }

    public JTextField getTxtPregu5() {
        return txtPregu5;
    }

    public void setTxtPregu5(JTextField txtPregu5) {
        this.txtPregu5 = txtPregu5;
    }

    public JTextField getTxtRespu1() {
        return txtRespu1;
    }

    public void setTxtRespu1(JTextField txtRespu1) {
        this.txtRespu1 = txtRespu1;
    }

    public JTextField getTxtRespu2() {
        return txtRespu2;
    }

    public void setTxtRespu2(JTextField txtRespu2) {
        this.txtRespu2 = txtRespu2;
    }

    public JTextField getTxtRespu3() {
        return txtRespu3;
    }

    public void setTxtRespu3(JTextField txtRespu3) {
        this.txtRespu3 = txtRespu3;
    }

    public JTextField getTxtRespu4() {
        return txtRespu4;
    }

    public void setTxtRespu4(JTextField txtRespu4) {
        this.txtRespu4 = txtRespu4;
    }

    public JTextField getTxtRespu5() {
        return txtRespu5;
    }

    public void setTxtRespu5(JTextField txtRespu5) {
        this.txtRespu5 = txtRespu5;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtNoEnc;
    private javax.swing.JTextField txtNomEnc;
    private javax.swing.JTextField txtPregu1;
    private javax.swing.JTextField txtPregu2;
    private javax.swing.JTextField txtPregu3;
    private javax.swing.JTextField txtPregu4;
    private javax.swing.JTextField txtPregu5;
    private javax.swing.JTextField txtRespu1;
    private javax.swing.JTextField txtRespu2;
    private javax.swing.JTextField txtRespu3;
    private javax.swing.JTextField txtRespu4;
    private javax.swing.JTextField txtRespu5;
    // End of variables declaration//GEN-END:variables
}
